### PR TITLE
Add Token MUSDT

### PR DESCRIPTION
**Pull request by mufengorg**

### CODE REVIEW

**Comment by hboon** [comment]
@mufengorg which chain (ID) is the token on?

**Comment by mufengorg** [comment]
9001/Matchain

**Comment by mufengorg** [comment]
I will update the token icon again, which may cause suspicion of plagiarism.

**Comment by mufengorg** [comment]
Type:	ERC20 (Ethereum)
ID:	0x67Dc36C19835Fa65Bf4B100FAC9a80A9E9280fB9
Name:	MUSDT
Symbol:	MUSDT
Decimals:	18
Website:	https://matchain.io
Explorer:	https://etherscan.io/token/0x67Dc36C19835Fa65Bf4B100FAC9a80A9E9280fB9
Description:	MUSDT
twitter:	https://twitter.com/MATCHCHAIN
github:	https://github.com/Matchain
telegram:	https://t.me/matchain2022
discord:	https://discord.com/invite/match
medium:	https://medium.com/@MATChain
reddit:	https://reddit.com/r/matchain2022

**Pull request closed without merging**
