### PR TITLE
0x0d450bf37ec899cca90ede124b3e69c9ae2f2f1c

### PR DESCRIPTION
**Pull request by fuyohasia**

### CODE REVIEW

**Comment by hboon** [comment]
@fuyohasia hi! Sorry it took a while. Would you be able to help with these:

* rename the folder to all lowercase? We have some problems with PRs ocassionally getting the casing wrong (we used to use EIP55 casing, but it was too easy to get it wrong)
* change the commit message to say what token this is for
* force push

**Comment by fuyohasia** [comment]
Folder rename to lowercase as suggested

**Comment by fuyohasia** [comment]
Sorry, any updates? Thanks

**Comment by hboon** [comment]
@fuyohasia sorry. Would you have grant me write access to your fork? The filename still isn't lowercased — it's a little tricky because the first commit has already added it, but with different casing, so git is picky. I can fix the commit for you and then merge if you like

**Comment by fuyohasia** [comment]
Yes you can have the right to do it on your own. I have no issue with it.Just let me know to get you the access as it seems it getting complicated.Thank youSent from my iPhoneOn 14 Oct 2022, at 10:15, Hwee-Boon Yar ***@***.***> wrote:﻿
@fuyohasia sorry. Would you have grant me write access to your fork? The filename still isn't lowercased — it's a little tricky because the first commit has already added it, but with different casing, so git is picky. I can fix the commit for you and then merge if you like

**Comment by hboon** [comment]
I have created #20 to replace this

**Comment by hboon** [comment]
Merged.

Thanks!

**Comment by fuyohasia** [comment]
Thank YouSent from my iPhoneOn 14 Oct 2022, at 12:48, Hwee-Boon Yar ***@***.***> wrote:﻿
I have created #20 to replace this

**Pull request closed without merging**
