### PR TITLE
0xa89af3d0aaf4c23ac2dc59875ef576e9a4254d30

### PR DESCRIPTION
**Pull request by PiBDT**
logo png

### CODE REVIEW

**Comment by PiBDT** [comment]
binance testnet chain id 97

**Review by PiBDT — COMMENTED** [review]
Logo

**Comment by hboon** [comment]
Hi! Thanks for the PR. There seems to be an empty file called `0xd013cff05836127116834e4bc2531830ddb27ceb`. Can you remove that from the PR?

And the image is called `logo.png.png`. Can you help rename it to `logo.png`?

**Comment by PiBDT** [comment]
Logo

**Review by PiBDT — COMMENTED** [review]
Logo

**Comment by PiBDT** [comment]
Hi Boon,
Feels great to hear from you.

I have made changes as asked by you.

Hope to get the icon display in Alpha Wallet.

Kind regards
Pi

**Review by PiBDT — COMMENTED** [review]
Logo

**Comment by hboon** [comment]
@PiBDT could you give me write access to the repo so I can fix it?

**Comment by hboon** [comment]
Thanks. Merged

**Comment by PiBDT** [comment]
@hboon. Thanks a lot for all your help.

**Comment by PiBDT** [comment]
@hboon
Please help merge this PR.

Kind Regards
Pi

**Pull request merged**
