### PR TITLE
Jj

### PR DESCRIPTION
**Pull request by wobytesnetwork**

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Hi, can you help make the image be called `0x01443a76022811e9182b8a56f5cc171aa13595f0/logo.png` in the commit/PR instead?

See https://github.com/AlphaWallet/iconassets/pull/26/files for an example

**Comment by wobytesnetwork** [comment]
logo

**Comment by wobytesnetwork** [comment]
> Hai, bisakah Anda membantu membuat gambar dipanggil `0x01443a76022811e9182b8a56f5cc171aa13595f0/logo.png`di komit/PR?
> 
> Lihat https://github.com/AlphaWallet/iconassets/pull/26/files sebagai contoh

logo

**Comment by wobytesnetwork** [comment]
logo

**Comment by wobytesnetwork** [comment]
/

**Comment by wobytesnetwork** [comment]
logo

**Pull request closed without merging**
