### PR TITLE
0x01443a76022811E9182B8a56f5cc171AA13595f0

### PR DESCRIPTION
**Pull request by wobytesplatform**
logo

### CODE REVIEW

**Comment by wobytesplatform** [comment]
@hboon

**Review by hboon — APPROVED** [review]

**Review by hboon — CHANGES_REQUESTED** [review]
@wobytesplatform oh wait. Can you help create the directory `0x01443a76022811e9182b8a56f5cc171aa13595f0` like you did earlier, keep the image file as `logo.png` and move it into the directory?

**Comment by wobytesplatform** [comment]
How do I change the PR, because I'm a new Github user
@hboon

**Comment by hboon** [comment]
> How do I change the PR, because I'm a new Github user

If you like, you can give me access to your forked repo, so I can make the changes for you. You should be able to do that by going to https://github.com/wobytesplatform/iconassets/settings/access and adding my username so I have write access to it.

**Comment by wobytesplatform** [comment]
@hboon 

Has my token logo been added

**Comment by hboon** [comment]
Done.

**Comment by hboon** [comment]
Thanks for the submission

**Pull request merged**
