### PR TITLE
0x01443a76022811e9182b8a56f5cc171aa13595f0

### PR DESCRIPTION
**Pull request by wobytesplatform**

### CODE REVIEW

**Comment by wobytesplatform** [comment]
@hboon 
https://github.com/AlphaWallet/iconassets/pull/33/commits/81cab267b28a6761ab77222a3c899b7ee5170c1b

**Review by wobytesplatform — COMMENTED** [review]
@hboon

**Comment by wobytesplatform** [comment]
logo

**Comment by hboon** [comment]
@wobytesplatform thanks for the PR, can you help with 2 things? —

* Change the directory name so it is all lowercase, from `0x01443a76022811E9182B8a56f5cc171AA13595f0` to `0x01443a76022811e9182b8a56f5cc171aa13595f0` (you might find it easier to rename it to something else locally first, anything, and then to the lowercase version because some OS don't like renaming just uppercase-lower case differences)
* The icon dimension looks correct (120x120), but looks jagged. It'll look much better if you have a higher-quality version (still 120x120)

**Comment by wobytesplatform** [comment]
@hboon 

Is it possible to use a logo icon with an image quality above 120x120 px?

**Comment by hboon** [comment]
It works, but 120x120 (or so) is a good balance of filesize and quality it can hold. I *think* it's possible that the icon you have has its quality compromised when it's resized. If you have a higher resolution icon, can you try downsize it again to 120x120? For example, if you look at this on a desktop monitor, it should be quite clear the the edges are jagged https://github.com/AlphaWallet/iconassets/pull/33#issuecomment-1510512706. It shouldn't be.

**Comment by wobytesplatform** [comment]
@hboon

**Comment by hboon** [comment]
@wobytesplatform directory name is good, but the image quality still isn't. Or do you have a higher res image you can upload into the comments her and we'll have a look?

**Comment by wobytesplatform** [comment]
@hboon I've tried reducing the size to 120x120 px but the image isn't too perfect, can you help me to perfect the image with a size of 120x120 px, I'll provide a high resolution image

**Comment by hboon** [comment]
Thanks, can you try replace the PR's with this? 

logo

**Comment by wobytesplatform** [comment]
232366257-192e367b-da69-4436-8f9a-0f5fdeedd165

Done

**Comment by hboon** [comment]
@wobytesplatform not by commenting; update the `logo.png` file in the PR and force push :)

**Pull request closed without merging**
