### PR TITLE
0xf549f4a5134ac3c7d427e907674633b0f233327d

### PR DESCRIPTION
**Pull request by PiBDT**
Logo

### CODE REVIEW

**Comment by PiBDT** [comment]
Hi @hboon ,
Can you please help merge this pull request.

**Comment by hboon** [comment]
Can you help provide a blockchain explorer (Etherscan etc) link to the token?

**Comment by PiBDT** [comment]
Chain id 97 Bsc Testnet

**Comment by PiBDT** [comment]
@hboon

Please help merge this PR.

**Comment by PiBDT** [comment]
@hboon 
Please help merge this PR.

**Comment by PiBDT** [comment]
@hboon

Awaiting your kind response.

Pi

**Comment by hboon** [comment]
@PiBDT I'm sorry, I somehow missed this completely. Would you help share a link to it on a blockchain explorer (eg. Etherscan) and describe it briefly?

**Comment by PiBDT** [comment]
@hboon Thankyou for your response. This project is closed.

**Comment by PiBDT** [comment]
@hboon

Please help merge this PR in Icon asset.
ChainID-97, bsctestnet.
Utility Token for nearby community.
Logo visual required for identification.

Kind regards
Pi

**Pull request closed without merging**
